config/routes.rb
Rails.application.routes.draw do
  root to: "awards#index"

  resources :awards, only: [:index, :create]
  
  get '/downloads/:repo/:login', to: 'awards#download', as: :download
  get '/downloads/:repo', to: 'awards#download_zip', as: :download_zip
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  def index
  end

  def download
    repo = JSON.parse($redis.get(awards_params[:repo]))
    author = repo.detect { |k| k['login'] == awards_params[:login] }
    pdf = PdfCreator.create(author['place'], author['login'], author['avatar_url'])

    respond_to do |f|
      f.pdf do
        send_data pdf, type: 'application/pdf'
      end
    end
  end

  def download_zip
    repo = JSON.parse($redis.get(awards_params[:repo]))
    respond_to do |f|
      f.zip do
        files = repo.map do |author|
          PdfCreator.create(author['place'], author['login'], author['avatar_url'])
        end

        compressed_pdfs = ZipCreator.compress(files)
        send_data compressed_pdfs.read, type: 'application/zip'
      end
    end
  end

  def create
    @repo_md5 = Digest::MD5.hexdigest(awards_params[:url])
    @result = FetchStats.call(url: awards_params[:url])

    if @result.success?
      $redis.set(@repo_md5, @result.contributors.to_json, ex: 900_000)
    end
  end

  private

  def awards_params
    params.permit(:login, :url, :repo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/awards/_error.slim
.result
  div.alert.alert-danger.w-75 role='alert'
    =error
    

app/views/awards/_table_awards.slim
.result
  table.table.w-50
    - result.contributors.each do |c|
      tr
        td = c[:login]
        td = link_to 'download pdf', download_path(repo, c[:login], format: :pdf)

  hr
  = link_to "download zip(#{result.contributors.size})", download_zip_path(repo, format: :zip)

app/views/awards/create.js.erb
<% if @result.success? %>
  $('.result').replaceWith("<%= j render partial: 'table_awards', locals: {result: @result, repo: @repo_md5 } %>");
<% else %>
  $('.result').replaceWith("<%= j render partial: 'error', locals: { error: @result[:message] } %>")
<% end %>

app/views/awards/index.slim
h1 GithubAwards
= form_with url: awards_path do |f|
  .form-row.align-items-center.w-100
    .col-auto.w-75
      = f.text_field :url, class: 'form-control', placeholder: 'GitHub repo url'
    .col-auto.w-25
      = f.submit 'search', class: 'btn btn-primary w-100'
.result
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GithubAwards</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container w-75'>
      <%= yield %>
    </div>
  </body>
</html>